# Generated by Django 6.0 on 2025-12-23 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Yazar Adı Soyadı')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Üniversite/Enstitü Adı')),
            ],
            options={
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Dil')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='ThesisType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tez Türü')),
            ],
            options={
                'db_table': 'thesis_type',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('thesis_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Tez Numarası')),
                ('title', models.CharField(max_length=500, verbose_name='Başlık')),
                ('abstract', models.TextField(verbose_name='Özet')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('num_pages', models.IntegerField(verbose_name='Sayfa Sayısı')),
                ('submission_date', models.DateField(verbose_name='Teslim Tarihi')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='gts.author', verbose_name='Yazar')),
                ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, to='gts.institute', verbose_name='Üniversite')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='gts.language', verbose_name='Dil')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='gts.thesistype', verbose_name='Tez Türü')),
            ],
            options={
                'db_table': 'thesis',
            },
        ),
    ]
