# Generated by Django 6.0 on 2025-12-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, verbose_name='Anahtar Kelime')),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='SubjectTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Konu Başlığı')),
            ],
            options={
                'db_table': 'subject_topic',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Danışman Adı Soyadı')),
            ],
            options={
                'db_table': 'supervisor',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Üniversite Adı')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'db_table': 'university',
            },
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name_plural': 'Theses'},
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Enstitü Adı'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='institute',
            field=models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, to='gts.institute', verbose_name='Enstitü'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='gts.keyword', verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='topics',
            field=models.ManyToManyField(to='gts.subjecttopic', verbose_name='Konu Başlıkları'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_supervised_theses', to='gts.supervisor', verbose_name='Eş Danışman'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_theses', to='gts.supervisor', verbose_name='Danışman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='university',
            field=models.ForeignKey(db_column='university_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='gts.university', verbose_name='Bağlı Olduğu Üniversite'),
            preserve_default=False,
        ),
    ]
