# Generated by Django 6.0 on 2025-12-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gts', '0002_keyword_subjecttopic_supervisor_university_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={},
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='topics',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Institute Name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='university',
            field=models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.CASCADE, to='gts.university', verbose_name='Affiliated University'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='subjecttopic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Supervisor Name'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='gts.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gts.supervisor'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='institute',
            field=models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, to='gts.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='language',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='gts.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='num_pages',
            field=models.IntegerField(verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='submission_date',
            field=models.DateField(verbose_name='Submission Date'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_theses', to='gts.supervisor', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='thesis_no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Thesis No'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='type',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='gts.thesistype', verbose_name='Thesis Type'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='thesistype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Thesis Type'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name='University Name'),
        ),
        migrations.AlterModelTable(
            name='thesis',
            table=None,
        ),
    ]
