# Generated by Django 6.0 on 2025-12-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gts', '0003_alter_thesis_options_remove_thesis_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='gts.keyword', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='topics',
            field=models.ManyToManyField(blank=True, to='gts.subjecttopic', verbose_name='Topics'),
        ),
    ]
